services:
  web:
    build: ./app
    command: gunicorn Task_Manager.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: